baseUrl=http://127.0.0.1:8080



## Use JDBC instead of Redis
#spring.session.store-type=jdbc
#spring.session.jdbc.initialize-schema=always
## H2 In-Memory Config
#spring.datasource.url=jdbc:h2:mem:sessiondb;DB_CLOSE_DELAY=-1
#spring.datasource.driverClassName=org.h2.Driver

logging.level.org.tbee.tutil.RateLimiter=debug
